INSERT INTO activities VALUES('Mining');
INSERT INTO activities VALUES('Missioning');
INSERT INTO activities VALUES('Ratting');
INSERT INTO activities VALUES('Other');

INSERT INTO ships VALUES('Pod', 0);
INSERT INTO ships VALUES('Abaddon', 136810000);
INSERT INTO ships VALUES('Absolution', 0);
INSERT INTO ships VALUES('Aeon', 0);
INSERT INTO ships VALUES('Amarr Navy Slicer', 0);
INSERT INTO ships VALUES('Amarr Shuttle', 0);
INSERT INTO ships VALUES('Anathema', 0);
INSERT INTO ships VALUES('Anshar', 0);
INSERT INTO ships VALUES('Apocalypse', 83705900);
INSERT INTO ships VALUES('Apocalypse Imperial Issue', 112500000);
INSERT INTO ships VALUES('Apocalypse Navy Issue', 108750000);
INSERT INTO ships VALUES('Arazu', 0);
INSERT INTO ships VALUES('Arbitrator', 3140640);
INSERT INTO ships VALUES('Archon', 0);
INSERT INTO ships VALUES('Ares', 0);
INSERT INTO ships VALUES('Ark', 0);
INSERT INTO ships VALUES('Armageddon', 50772000);
INSERT INTO ships VALUES('Armageddon Imperial Issue', 66250000);
INSERT INTO ships VALUES('Ashimmu', 0);
INSERT INTO ships VALUES('Astarte', 0);
INSERT INTO ships VALUES('Atron', 0);
INSERT INTO ships VALUES('Augoror', 3200000);
INSERT INTO ships VALUES('Avatar', 0);
INSERT INTO ships VALUES('Badger', 0);
INSERT INTO ships VALUES('Badger Mark II', 0);
INSERT INTO ships VALUES('Bantam', 0);
INSERT INTO ships VALUES('Basilisk', 0);
INSERT INTO ships VALUES('Bellicose', 3698620);
INSERT INTO ships VALUES('Bestower', 0);
INSERT INTO ships VALUES('Blackbird', 3260930);
INSERT INTO ships VALUES('Breacher', 0);
INSERT INTO ships VALUES('Broadsword', 0);
INSERT INTO ships VALUES('Brutix', 20145500);
INSERT INTO ships VALUES('Burst', 0);
INSERT INTO ships VALUES('Bustard', 0);
INSERT INTO ships VALUES('Buzzard', 0);
INSERT INTO ships VALUES('Caldari Navy Hookbill', 0);
INSERT INTO ships VALUES('Caldari Shuttle', 0);
INSERT INTO ships VALUES('Caracal', 3470410);
INSERT INTO ships VALUES('Catalyst', 0);
INSERT INTO ships VALUES('Celestis', 3203410);
INSERT INTO ships VALUES('Cerberus', 0);
INSERT INTO ships VALUES('Charon', 0);
INSERT INTO ships VALUES('Cheetah', 0);
INSERT INTO ships VALUES('Chimera', 0);
INSERT INTO ships VALUES('Claw', 0);
INSERT INTO ships VALUES('Claymore', 0);
INSERT INTO ships VALUES('Coercer', 0);
INSERT INTO ships VALUES('Condor', 0);
INSERT INTO ships VALUES('Cormorant', 0);
INSERT INTO ships VALUES('Covetor', 0);
INSERT INTO ships VALUES('Crane', 0);
INSERT INTO ships VALUES('Crow', 0);
INSERT INTO ships VALUES('Crucifier', 0);
INSERT INTO ships VALUES('Cruor', 0);
INSERT INTO ships VALUES('Crusader', 0);
INSERT INTO ships VALUES('Curse', 0);
INSERT INTO ships VALUES('Cyclone', 19121300);
INSERT INTO ships VALUES('Cynabal', 0);
INSERT INTO ships VALUES('Damnation', 0);
INSERT INTO ships VALUES('Daredevil', 0);
INSERT INTO ships VALUES('Deimos', 0);
INSERT INTO ships VALUES('Devoter', 0);
INSERT INTO ships VALUES('Dominix', 51604200);
INSERT INTO ships VALUES('Drake', 30409900);
INSERT INTO ships VALUES('Dramiel', 0);
INSERT INTO ships VALUES('Eagle', 0);
INSERT INTO ships VALUES('Enyo', 0);
INSERT INTO ships VALUES('Eos', 0);
INSERT INTO ships VALUES('Erebus', 0);
INSERT INTO ships VALUES('Eris', 0);
INSERT INTO ships VALUES('Executioner', 0);
INSERT INTO ships VALUES('Exequror', 3509560);
INSERT INTO ships VALUES('Falcon', 0);
INSERT INTO ships VALUES('Fenrir', 0);
INSERT INTO ships VALUES('Ferox', 23871600);
INSERT INTO ships VALUES('Flycatcher', 0);
INSERT INTO ships VALUES('Gallente Navy Comet', 0);
INSERT INTO ships VALUES('Gallente Shuttle', 0);
INSERT INTO ships VALUES('Gold Magnate', 0);
INSERT INTO ships VALUES('Golem', 0);
INSERT INTO ships VALUES('Griffin', 0);
INSERT INTO ships VALUES('Guardian', 0);
INSERT INTO ships VALUES('Harbinger', 37313400);
INSERT INTO ships VALUES('Harpy', 0);
INSERT INTO ships VALUES('Hawk', 0);
INSERT INTO ships VALUES('Hel', 0);
INSERT INTO ships VALUES('Helios', 0);
INSERT INTO ships VALUES('Heretic', 0);
INSERT INTO ships VALUES('Heron', 0);
INSERT INTO ships VALUES('Hoarder', 0);
INSERT INTO ships VALUES('Hound', 0);
INSERT INTO ships VALUES('Huginn', 0);
INSERT INTO ships VALUES('Hulk', 0);
INSERT INTO ships VALUES('Hurricane', 32114000);
INSERT INTO ships VALUES('Hyena', 0);
INSERT INTO ships VALUES('Hyperion', 132243000);
INSERT INTO ships VALUES('Ibis', 0);
INSERT INTO ships VALUES('Imicus', 0);
INSERT INTO ships VALUES('Impairor', 0);
INSERT INTO ships VALUES('Impel', 0);
INSERT INTO ships VALUES('Incursus', 0);
INSERT INTO ships VALUES('Inquisitor', 0);
INSERT INTO ships VALUES('Ishkur', 0);
INSERT INTO ships VALUES('Ishtar', 0);
INSERT INTO ships VALUES('Iteron', 0);
INSERT INTO ships VALUES('Iteron Mark II', 0);
INSERT INTO ships VALUES('Iteron Mark III', 0);
INSERT INTO ships VALUES('Iteron Mark IV', 0);
INSERT INTO ships VALUES('Iteron Mark V', 0);
INSERT INTO ships VALUES('Jaguar', 0);
INSERT INTO ships VALUES('Keres', 0);
INSERT INTO ships VALUES('Kestrel', 0);
INSERT INTO ships VALUES('Kitsune', 0);
INSERT INTO ships VALUES('Kronos', 0);
INSERT INTO ships VALUES('Lachesis', 0);
INSERT INTO ships VALUES('Leviathan', 0);
INSERT INTO ships VALUES('Machariel', 0);
INSERT INTO ships VALUES('Mackinaw', 0);
INSERT INTO ships VALUES('Maelstrom', 113417000);
INSERT INTO ships VALUES('Magnate', 0);
INSERT INTO ships VALUES('Malediction', 0);
INSERT INTO ships VALUES('Maller', 7717860);
INSERT INTO ships VALUES('Mammoth', 0);
INSERT INTO ships VALUES('Manticore', 0);
INSERT INTO ships VALUES('Mastodon', 0);
INSERT INTO ships VALUES('Maulus', 0);
INSERT INTO ships VALUES('Megathron', 81981900);
INSERT INTO ships VALUES('Megathron Navy Issue', 108750000);
INSERT INTO ships VALUES('Merlin', 0);
INSERT INTO ships VALUES('Minmatar Shuttle', 0);
INSERT INTO ships VALUES('Moa', 5988570  	);
INSERT INTO ships VALUES('Moros', 0);
INSERT INTO ships VALUES('Muninn', 0);
INSERT INTO ships VALUES('Myrmidon', 31330900);
INSERT INTO ships VALUES('Naglfar', 0);
INSERT INTO ships VALUES('Navitas', 0);
INSERT INTO ships VALUES('Nemesis', 0);
INSERT INTO ships VALUES('Nidhoggur', 0);
INSERT INTO ships VALUES('Nighthawk', 0);
INSERT INTO ships VALUES('Nightmare', 0);
INSERT INTO ships VALUES('Nomad', 0);
INSERT INTO ships VALUES('Nyx', 0);
INSERT INTO ships VALUES('Obelisk', 0);
INSERT INTO ships VALUES('Occator', 0);
INSERT INTO ships VALUES('Omen', 4524580);
INSERT INTO ships VALUES('Oneiros', 0);
INSERT INTO ships VALUES('Onyx', 0);
INSERT INTO ships VALUES('Osprey', 2613440);
INSERT INTO ships VALUES('Paladin', 0);
INSERT INTO ships VALUES('Panther', 0);
INSERT INTO ships VALUES('Phantasm', 0);
INSERT INTO ships VALUES('Phobos', 0);
INSERT INTO ships VALUES('Phoenix', 0);
INSERT INTO ships VALUES('Pilgrim', 0);
INSERT INTO ships VALUES('Probe', 0);
INSERT INTO ships VALUES('Procurer', 0);
INSERT INTO ships VALUES('Prophecy', 23032900);
INSERT INTO ships VALUES('Prorator', 0);
INSERT INTO ships VALUES('Providence', 0);
INSERT INTO ships VALUES('Prowler', 0);
INSERT INTO ships VALUES('Punisher', 0);
INSERT INTO ships VALUES('Purifier', 0);
INSERT INTO ships VALUES('Ragnarok', 0);
INSERT INTO ships VALUES('Rapier', 0);
INSERT INTO ships VALUES('Raptor', 0);
INSERT INTO ships VALUES('Rattlesnake', 108750000);
INSERT INTO ships VALUES('Raven', 84221400);
INSERT INTO ships VALUES('Raven Navy Issue', 108750000);
INSERT INTO ships VALUES('Reaper', 0);
INSERT INTO ships VALUES('Redeemer', 0);
INSERT INTO ships VALUES('Republic Fleet Firetail', 0);
INSERT INTO ships VALUES('Retribution', 0);
INSERT INTO ships VALUES('Retriever', 0);
INSERT INTO ships VALUES('Revelation', 0);
INSERT INTO ships VALUES('Rhea', 0);
INSERT INTO ships VALUES('Rifter', 0);
INSERT INTO ships VALUES('Rokh', 0);
INSERT INTO ships VALUES('Rook', 0);
INSERT INTO ships VALUES('Rorqual', 0);
INSERT INTO ships VALUES('Rupture', 6003840);
INSERT INTO ships VALUES('Sabre', 0);
INSERT INTO ships VALUES('Sacrilege', 0);
INSERT INTO ships VALUES('Scimitar', 0);
INSERT INTO ships VALUES('Scorpion', 0);
INSERT INTO ships VALUES('Scythe', 2935320);
INSERT INTO ships VALUES('Sentinel', 0);
INSERT INTO ships VALUES('Sigil', 0);
INSERT INTO ships VALUES('Silver Magnate', 0);
INSERT INTO ships VALUES('Sin', 0);
INSERT INTO ships VALUES('Skiff', 0);
INSERT INTO ships VALUES('Slasher', 0);
INSERT INTO ships VALUES('Sleipnir', 0);
INSERT INTO ships VALUES('Stabber', 3907580);
INSERT INTO ships VALUES('Stiletto', 0);
INSERT INTO ships VALUES('Succubus', 0);
INSERT INTO ships VALUES('Taranis', 0);
INSERT INTO ships VALUES('Tempest', 82926400);
INSERT INTO ships VALUES('Tempest Fleet Issue', 108750000);
INSERT INTO ships VALUES('Thanatos', 0);
INSERT INTO ships VALUES('Thorax', 5856020);
INSERT INTO ships VALUES('Thrasher', 0);
INSERT INTO ships VALUES('Tormentor', 0);
INSERT INTO ships VALUES('Tristan', 0);
INSERT INTO ships VALUES('Typhoon', 58967300);
INSERT INTO ships VALUES('Vagabond', 0);
INSERT INTO ships VALUES('Vargur', 0);
INSERT INTO ships VALUES('Velator', 0);
INSERT INTO ships VALUES('Vengeance', 0);
INSERT INTO ships VALUES('Vexor', 4069600);
INSERT INTO ships VALUES('Viator', 0);
INSERT INTO ships VALUES('Vigil', 0);
INSERT INTO ships VALUES('Vulture', 0);
INSERT INTO ships VALUES('Widow', 0);
INSERT INTO ships VALUES('Wolf', 0);
INSERT INTO ships VALUES('Worm', 0);
INSERT INTO ships VALUES('Wreathe', 0);
INSERT INTO ships VALUES('Wyvern', 0);
INSERT INTO ships VALUES('Zealot', 0);
INSERT INTO ships VALUES('Other', 0);